# Generated by Django 5.0.7 on 2024-07-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('fundacja', 'Fundacja'), ('organizacja_pozarządowa', 'Organizacja pozarządowa'), ('zbiórka_lokalna', 'Zbiórka lokalna')], default='fundacja', max_length=50)),
                ('categories', models.ManyToManyField(to='categories.category')),
            ],
        ),
    ]
